export const JOB_STATUS = {
    PENDING: 'pending',
    INTERVIEW: 'interview',
    DECLINED: 'declined',
}

export const JOB_TYPE = {
    FULL_TIME: 'full-time',
    PART_TIME: 'part-time',
    INTERNSHIP: 'internship'
}

export const JOB_SORT_BY = {
    NEWEST_FIRST: 'newest',
    OLDEST_FIRST: 'oldest',
    ASCENDING: 'a-z',
    DESCENDING: 'z-a'
}

export const SORT_BY = {
    NEWEST_FIRST: 'newest',
    OLDEST_FIRST: 'oldest',
    ASCENDING: 'a-z',
    DESCENDING: 'z-a',
    NOKURSI_ASC: 'No Kursi - ASC',
    NOKURSI_DSC: 'No Kursi - DESC'
}

export const JURUSAN = {
    JTI: 'JTI',
    JTIN: 'JTIN',
    AKTP: 'AKTP'
}

export const ISREGIS = {
    TRUE: true,
    FALSE: false,
}

export const PRODI = {
    D3_TEKNIK_ELEKTRONIKA: 'D3 TEKNIK ELEKTRONIKA',
    D3_TEKNIK_MEKATRONIKA: 'D3 TEKNIK MEKATRONIKA',
    D3_TEKNIK_KOMPUTER: 'D3 TEKNIK KOMPUTER',
    D4_AKUNTANSI_PERPAJAKAN: 'D4 AKUNTANSI PERPAJAKAN',
    D4_TEKNIK_ELEKTRONIKA_TELEKOMUNIKASI: 'D4 TEKNIK ELEKTRONIKA TELEKOMUNIKASI',
    D4_SISTEM_INFORMASI: 'D4 SISTEM INFORMASI',
    D4_TEKNIK_INFORMATIKA: 'D4 TEKNIK INFORMATIKA',
    D4_TEKNIK_LISTRIK: 'D4 TEKNIK LISTRIK',
    D4_TEKNOLOGI_REKAYASA_JARINGAN_TELEKOMUNIKASI: 'D4 TEKNOLOGI REKAYASA JARINGAN TELEKOMUNIKASI',
    D4_TEKNIK_MESIN: 'D4 TEKNIK MESIN',
    S2_MAGISTER_TERAPAN_TEKNIK_KOMPUTER: 'S2 MAGISTER TERAPAN TEKNIK KOMPUTER',
    D4_TEKNOLOGI_REKAYASA_MEKATRONIKA: 'D4 TEKNOLOGI REKAYASA MEKATRONIKA',
    D4_TEKNOLOGI_REKAYASA_SISTEM_ELEKTRONIKA: 'D4 TEKNOLOGI REKAYASA SISTEM ELEKTRONIKA',
    D4_TEKNOLOGI_REKAYASA_KOMPUTER: 'D4 TEKNOLOGI REKAYASA KOMPUTER',
}