export const JOB_STATUS = {
    PENDING: 'pending',
    INTERVIEW: 'interview',
    DECLINED: 'declined',
}

export const JOB_TYPE = {
    FULL_TIME: 'full-time',
    PART_TIME: 'part-time',
    INTERNSHIP: 'internship'
}

export const JOB_SORT_BY = {
    NEWEST_FIRST: 'newest',
    OLDEST_FIRST: 'oldest',
    ASCENDING: 'a-z',
    DESCENDING: 'z-a'
}

export const SORT_BY = {
    NEWEST_FIRST: 'newest',
    OLDEST_FIRST: 'oldest',
    ASCENDING: 'a-z',
    DESCENDING: 'z-a',
    NOKURSI_ASC: 'No Kursi - ASC',
    NOKURSI_DSC: 'No Kursi - DESC'
}

export const JURUSAN = {
    JTI: 'JTI',
    JTIN: 'JTIN',
    AKTP: 'AKTP'
}

export const ISREGIS = {
    TRUE: true,
    FALSE: false,
}

export const PRODI = {
    D3_TEKNIK_ELEKTRONIKA: 'D3 TEKNIK ELEKTRONIKA',
    D3_TEKNIK_MEKATRONIKA: 'D3 TEKNIK MEKATRONIKA',
    D3_TEKNIK_KOMPUTER: 'D3 TEKNIK KOMPUTER',
    D4_AKUNTANSI_PERPAJAKAN: 'D4 AKUNTANSI PERPAJAKAN',
    D4_TEKNIK_ELEKTRONIKA_TELEKOMUNIKASI: 'D4 TEKNIK ELEKTRONIKA TELEKOMUNIKASI',
    D4_SISTEM_INFORMASI: 'D4 SISTEM INFORMASI',
    D4_TEKNIK_INFORMATIKA: 'D4 TEKNIK INFORMATIKA',
    D4_TEKNIK_LISTRIK: 'D4 TEKNIK LISTRIK',
    D4_TEKNOLOGI_REKAYASA_JARINGAN_TELEKOMUNIKASI: 'D4 TEKNOLOGI REKAYASA JARINGAN TELEKOMUNIKASI',
    D4_TEKNIK_MESIN: 'D4 TEKNIK MESIN',
    S2_MAGISTER_TERAPAN_TEKNIK_KOMPUTER: 'S2 MAGISTER TERAPAN TEKNIK KOMPUTER',
    D4_TEKNOLOGI_REKAYASA_MEKATRONIKA: 'D4 TEKNOLOGI REKAYASA MEKATRONIKA',
    D4_TEKNOLOGI_REKAYASA_SISTEM_ELEKTRONIKA: 'D4 TEKNOLOGI REKAYASA SISTEM ELEKTRONIKA',
    D4_TEKNOLOGI_REKAYASA_KOMPUTER: 'D4 TEKNOLOGI REKAYASA KOMPUTER',
}
export const PRODII = [
    { "name": "D3 TEKNIK ELEKTRONIKA", "register": 450, "unregister": 455 },
    { "name": "D3 TEKNIK MEKATRONIKA", "register": 163, "unregister": 145 },
    { "name": "D3 TEKNIK KOMPUTER", "register": 427, "unregister": 461 },
    { "name": "D4 AKUNTANSI PERPAJAKAN", "register": 271, "unregister": 13 },
    { "name": "D4 TEKNIK ELEKTRONIKA TELEKOMUNIKASI", "register": 169, "unregister": 386 },
    { "name": "D4 SISTEM INFORMASI", "register": 480, "unregister": 472 },
    { "name": "D4 TEKNIK INFORMATIKA", "register": 366, "unregister": 54 },
    { "name": "D4 TEKNIK LISTRIK", "register": 203, "unregister": 281 },
    { "name": "D4 TEKNOLOGI REKAYASA JARINGAN TELEKOMUNIKASI", "register": 198, "unregister": 384 },
    { "name": "D4 TEKNIK MESIN", "register": 268, "unregister": 370 },
    { "name": "S2 MAGISTER TERAPAN TEKNIK KOMPUTER", "register": 395, "unregister": 154 },
    { "name": "D4 TEKNOLOGI REKAYASA MEKATRONIKA", "register": 283, "unregister": 439 },
    { "name": "D4 TEKNOLOGI REKAYASA SISTEM ELEKTRONIKA", "register": 308, "unregister": 153 },
    { "name": "D4 TEKNOLOGI REKAYASA KOMPUTER", "register": 93, "unregister": 415 }
]


const Registered = {
    'D3 TEKNIK ELEKTRONIKA': 0,
    'D3 TEKNIK MEKATRONIKA': 0,
    'D3 TEKNIK KOMPUTER': 0,
    'D4 AKUNTANSI PERPAJAKAN': 0,
    'D4 TEKNIK ELEKTRONIKA TELEKOMUNIKASI': 0,
    'D4 SISTEM INFORMASI': 0,
    'D4 TEKNIK INFORMATIKA': 3,
    'D4 TEKNIK LISTRIK': 0,
    'D4 TEKNOLOGI REKAYASA JARINGAN TELEKOMUNIKASI': 0,
    'D4 TEKNIK MESIN': 0,
    'S2 MAGISTER TERAPAN TEKNIK KOMPUTER': 6,
    'D4 TEKNOLOGI REKAYASA MEKATRONIKA': 0,
    'D4 TEKNOLOGI REKAYASA SISTEM ELEKTRONIKA': 0,
    'D4 TEKNOLOGI REKAYASA KOMPUTER': 0
}